import html2canvas from "html2canvas"
import jsPDF from "jspdf"

export async function exportToPDF(
  elementId: string,
  fileName: string,
  title: string,
  companyName: string = "AI-Powered Dashboard"
) {
  try {
    const element = document.getElementById(elementId)
    if (!element) {
      console.error(`Element with id "${elementId}" not found`)
      return
    }

    // Save original styles
    const originalStyle = element.getAttribute("style") || ""
    const originalAnimation = element.style.animation

    // Disable animations and handle CSS parsing
    element.style.animation = "none"
    element.style.filter = "none"

    // Create canvas from the element with error suppression for oklab parsing
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#0F172A", // dark background
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight,
      allowTaint: true,
      onclone: (clonedDocument) => {
        // Remove @supports rules with oklab in the cloned document
        const styles = clonedDocument.querySelectorAll("style")
        styles.forEach((style) => {
          if (style.textContent && style.textContent.includes("oklab")) {
            style.textContent = style.textContent.replace(
              /@supports\s*\([^)]*oklab[^)]*\)\s*\{[^}]*\}/g,
              ""
            )
          }
        })
      },
    })

    // Restore animations
    element.style.animation = originalAnimation
    if (originalStyle) {
      element.setAttribute("style", originalStyle)
    }

    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 15

    // Add title and header
    pdf.setFontSize(20)
    pdf.setTextColor(33, 150, 243) // primary blue
    pdf.text("Business Analysis & Prediction Report", margin, margin + 5)

    pdf.setFontSize(11)
    pdf.setTextColor(148, 163, 184) // muted foreground
    pdf.text(`${companyName}`, margin, margin + 15)
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, margin + 22)

    // Add divider line
    pdf.setDrawColor(30, 41, 59) // border color
    pdf.line(margin, margin + 28, pageWidth - margin, margin + 28)

    // Calculate image dimensions to fit page
    const contentWidth = pageWidth - 2 * margin
    const contentHeight = (canvas.height * contentWidth) / canvas.width
    let yPosition = margin + 35

    // Add content image, splitting across multiple pages if needed
    let remainingHeight = contentHeight
    let imgYOffset = 0

    while (remainingHeight > 0) {
      const availableHeight = pageHeight - yPosition - margin - 15 // leave space for footer

      if (remainingHeight <= availableHeight) {
        // Fits on current page
        pdf.addImage(
          imgData,
          "PNG",
          margin,
          yPosition,
          contentWidth,
          remainingHeight,
          undefined,
          "FAST",
          0,
          imgYOffset
        )
        remainingHeight = 0
      } else {
        // Need to split across pages
        const heightToCrop = (availableHeight * canvas.height) / contentHeight
        const croppedCanvas = document.createElement("canvas")
        croppedCanvas.width = canvas.width
        croppedCanvas.height = heightToCrop

        const ctx = croppedCanvas.getContext("2d")
        if (ctx) {
          ctx.drawImage(canvas, 0, imgYOffset, canvas.width, heightToCrop, 0, 0, canvas.width, heightToCrop)
          const croppedImgData = croppedCanvas.toDataURL("image/png")
          pdf.addImage(croppedImgData, "PNG", margin, yPosition, contentWidth, availableHeight)
        }

        remainingHeight -= availableHeight
        imgYOffset += heightToCrop

        // Add new page
        pdf.addPage()
        yPosition = margin
      }
    }

    // Add footer to all pages
    const totalPages = pdf.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      pdf.setFontSize(9)
      pdf.setTextColor(100, 116, 139) // muted foreground
      pdf.text("Generated by BAPS – Business Analysis System", margin, pageHeight - 10)
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 10)
    }

    // Download PDF
    pdf.save(fileName)
  } catch (error) {
    console.error("Error exporting to PDF:", error)
    alert("Failed to export PDF. Please try again.")
  }
}
