import { useNavigate } from "react-router-dom";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { SectionHeader } from "@/components/ui/section-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { Button } from "@/components/ui/button";
import {
  History,
  Building2,
  Eye,
  Download,
  Clock,
  Plus,
  FileText,
  Sparkles,
} from "lucide-react";
import { useCompany } from "@/context/CompanyContext";
import { toast } from "sonner";

export default function HistoryPage() {
  const navigate = useNavigate();
  const { analyses } = useCompany();

  const getHealthScoreVariant = (score: number) => {
    if (score >= 75) return "success";
    if (score >= 50) return "warning";
    return "danger";
  };

  const getRiskVariant = (risk: string) => {
    switch (risk) {
      case "Low":
        return "success";
      case "Medium":
        return "warning";
      case "High":
        return "danger";
      default:
        return "default";
    }
  };

  const handleView = (id: string) => {
    // Navigate to dashboard with the analysis data
    navigate("/dashboard");
    toast.info("Viewing analysis report");
  };

  const handleExport = (analysis: typeof analyses[0]) => {
    // Generate and download PDF report
    const reportContent = `
BUSINESS ANALYSIS REPORT
========================

Company: ${analysis.companyName}
Industry: ${analysis.industry}
Stage: ${analysis.stage}
Analysis Date: ${analysis.date}

HEALTH METRICS
--------------
Overall Health Score: ${analysis.healthScore}/100
Risk Level: ${analysis.riskLevel}

SUMMARY
-------
This report provides a comprehensive analysis of ${analysis.companyName}'s 
business health and performance metrics. The company operates in the 
${analysis.industry} sector and is currently at the ${analysis.stage} stage.

Based on the analysis, the company has a health score of ${analysis.healthScore}/100 
with a ${analysis.riskLevel.toLowerCase()} risk level.

---
Generated by BizAnalytics
Report ID: ${analysis.id}
    `;

    // Create blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${analysis.companyName.replace(/\s+/g, '_')}_Report_${analysis.date}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    toast.success("Report exported!", {
      description: `${analysis.companyName} report has been downloaded.`,
    });
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="relative">
          <div className="absolute inset-0 bg-gradient-to-r from-primary/5 via-transparent to-transparent rounded-3xl" />
          <div className="relative flex items-center justify-between gap-4 p-6">
            <div className="flex items-center gap-4">
              <div className="relative">
                <div className="absolute inset-0 bg-primary/20 blur-xl rounded-full" />
                <div className="relative w-14 h-14 rounded-2xl bg-gradient-to-br from-primary/30 to-cyan-500/20 border border-primary/20 flex items-center justify-center">
                  <History className="w-7 h-7 text-primary" />
                </div>
              </div>
              <div>
                <h1 className="text-2xl font-bold tracking-tight">Report History</h1>
                <p className="text-muted-foreground flex items-center gap-2 mt-1">
                  <Sparkles className="w-4 h-4 text-primary" />
                  View and manage your business analysis reports
                </p>
              </div>
            </div>
            <Button 
              onClick={() => navigate("/input")}
              className="bg-gradient-primary hover:opacity-90 text-primary-foreground"
            >
              <Plus className="w-4 h-4 mr-2" />
              New Analysis
            </Button>
          </div>
        </div>

        {/* Analysis List */}
        {analyses.length === 0 ? (
          <div className="premium-card p-12 text-center">
            <div className="w-20 h-20 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-6">
              <FileText className="w-10 h-10 text-primary/60" />
            </div>
            <h3 className="text-xl font-semibold mb-2">No Reports Yet</h3>
            <p className="text-muted-foreground mb-6 max-w-md mx-auto">
              Start by adding your company details to generate your first business analysis report.
            </p>
            <Button 
              onClick={() => navigate("/input")}
              className="bg-gradient-primary hover:opacity-90 text-primary-foreground"
            >
              <Plus className="w-4 h-4 mr-2" />
              Add Company Details
            </Button>
          </div>
        ) : (
          <div className="premium-card overflow-hidden">
            <div className="p-5 border-b border-border/50">
              <div className="flex items-center justify-between">
                <h3 className="font-semibold text-lg">Your Analysis Reports</h3>
                <span className="text-sm text-muted-foreground">{analyses.length} report{analyses.length !== 1 ? 's' : ''}</span>
              </div>
            </div>
            <div className="divide-y divide-border/50">
              {analyses.map((analysis) => (
                <div
                  key={analysis.id}
                  className="p-5 hover:bg-secondary/20 transition-colors"
                >
                  <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
                    <div className="flex items-start gap-4">
                      <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-primary/20 to-cyan-500/10 border border-primary/20 flex items-center justify-center flex-shrink-0">
                        <Building2 className="w-7 h-7 text-primary" />
                      </div>
                      <div>
                        <h4 className="font-semibold text-lg">{analysis.companyName}</h4>
                        <div className="flex items-center gap-2 mt-1">
                          <span className="text-sm text-muted-foreground">{analysis.industry}</span>
                          <span className="text-muted-foreground/50">•</span>
                          <span className="text-sm text-muted-foreground">{analysis.stage}</span>
                        </div>
                        <div className="flex items-center gap-2 mt-2">
                          <Clock className="w-3.5 h-3.5 text-muted-foreground" />
                          <span className="text-xs text-muted-foreground">{analysis.date}</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
                      <div className="flex items-center gap-4">
                        <div className="text-center">
                          <p className="text-xs text-muted-foreground mb-1.5">Health Score</p>
                          <StatusBadge
                            label={`${analysis.healthScore}/100`}
                            variant={getHealthScoreVariant(analysis.healthScore) as "success" | "warning" | "danger"}
                            size="sm"
                          />
                        </div>
                        <div className="text-center">
                          <p className="text-xs text-muted-foreground mb-1.5">Risk Level</p>
                          <StatusBadge
                            label={analysis.riskLevel}
                            variant={getRiskVariant(analysis.riskLevel) as "success" | "warning" | "danger"}
                            size="sm"
                          />
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button 
                          variant="outline" 
                          size="sm" 
                          className="gap-1.5 hover:bg-primary/10 hover:text-primary hover:border-primary/30"
                          onClick={() => handleView(analysis.id)}
                        >
                          <Eye className="w-4 h-4" />
                          View
                        </Button>
                        <Button 
                          variant="outline" 
                          size="sm" 
                          className="gap-1.5 hover:bg-emerald-500/10 hover:text-emerald-400 hover:border-emerald-500/30"
                          onClick={() => handleExport(analysis)}
                        >
                          <Download className="w-4 h-4" />
                          Export
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Export Note */}
        {analyses.length > 0 && (
          <div className="premium-card p-4 flex items-start gap-3 border border-primary/20">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
              <Download className="w-5 h-5 text-primary" />
            </div>
            <div>
              <p className="text-sm font-medium">Export Reports</p>
              <p className="text-xs text-muted-foreground mt-1">
                Click the export button to download a detailed report of any analysis. 
                Reports include all metrics and business health information.
              </p>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
