export async function exportToPDFBackend(
  fileName: string,
  companyName: string = "AI-Powered Dashboard"
) {
  try {
    console.log("Starting backend PDF export...")
    
    // Get company data from localStorage
    const storedData = localStorage.getItem('companyAnalysisData')
    const companyData = storedData ? JSON.parse(storedData) : {}
    
    // Call backend API for PDF generation
    const response = await fetch('http://localhost:8000/api/export-analysis', {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'Accept': 'application/pdf'
      },
      body: JSON.stringify(companyData)
    })
    
    if (!response.ok) {
      throw new Error(`Backend export failed: ${response.status}`)
    }
    
    // Get PDF blob
    const blob = await response.blob()
    
    // Check if it's actually a PDF
    if (blob.type !== 'application/pdf') {
      console.warn('Response is not PDF, blob type:', blob.type)
      // Try to get text to see error message
      const text = await blob.text()
      console.error('Backend response:', text)
      throw new Error('Server did not return a PDF file')
    }
    
    // Create download link
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = fileName
    document.body.appendChild(a)
    a.click()
    
    // Cleanup
    window.URL.revokeObjectURL(url)
    document.body.removeChild(a)
    
    console.log("PDF exported successfully from backend")
    
  } catch (error) {
    console.error("Backend PDF export error:", error)
    
    // Show user-friendly error
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred'
    
    // Try to create a simple text report as fallback
    try {
      await createFallbackReport(companyData, fileName)
    } catch (fallbackError) {
      console.error("Fallback report also failed:", fallbackError)
      alert(`PDF export failed: ${errorMessage}\n\nPlease try again or contact support.`)
    }
  }
}

async function createFallbackReport(companyData: any, fileName: string) {
  console.log("Creating fallback text report...")
  
  // Create simple text report
  const report = `
BUSINESS ANALYSIS REPORT
========================

Company: ${companyData.companyName || 'N/A'}
Generated: ${new Date().toLocaleDateString()}

COMPANY INFORMATION
------------------
Name: ${companyData.companyName || 'N/A'}
Industry: ${companyData.industry || 'N/A'}
Revenue: $${(companyData.revenue || '0').toLocaleString()}
Growth Rate: ${companyData.growthRate || 'N/A'}%
Team Size: ${companyData.teamSize || 'N/A'}
Customer Count: ${companyData.customerCount || 'N/A'}

FINANCIAL METRICS
----------------
Revenue: $${(companyData.revenue || '0').toLocaleString()}
Expenses: $${(companyData.expenses || '0').toLocaleString()}
Profit Margin: ${companyData.profitMargin || 'N/A'}%
Burn Rate: $${(companyData.burnRate || '0').toLocaleString()}/month
Cash Balance: $${(companyData.cashBalance || '0').toLocaleString()

MARKET METRICS
-------------
Market Size: $${(companyData.marketSize || '0').toLocaleString()}
Competitors: ${companyData.competitorCount || 'N/A'}
Market Share: ${companyData.marketShare || 'N/A'}%
Industry Growth: ${companyData.industryGrowthRate || 'N/A'}%

CUSTOMER METRICS
----------------
Churn Rate: ${companyData.churnRate || 'N/A'}%
NPS Score: ${companyData.nps || 'N/A'}
Customer Satisfaction: ${companyData.customerSatisfaction || 'N/A'}/5

Generated by NexusAI Business Analytics System
`.trim()
  
  // Create and download text file
  const blob = new Blob([report], { type: 'text/plain' })
  const url = window.URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = fileName.replace('.pdf', '.txt')
  document.body.appendChild(a)
  a.click()
  window.URL.revokeObjectURL(url)
  document.body.removeChild(a)
  
  console.log("Fallback report created successfully")
  alert('PDF export failed, but a text report has been downloaded instead.')
}
