import html2canvas from "html2canvas"
import jsPDF from "jspdf"

export async function exportToPDFSimple(
  elementId: string,
  fileName: string,
  title: string,
  companyName: string = "AI-Powered Dashboard"
) {
  try {
    const element = document.getElementById(elementId)
    if (!element) {
      console.error(`Element with id "${elementId}" not found`)
      return
    }

    console.log("Starting PDF export...")

    // Temporarily hide problematic elements
    const originalDisplays = new Map()
    const problematicElements = element.querySelectorAll('*')
    
    problematicElements.forEach(el => {
      const element = el as HTMLElement
      if (element.style) {
        // Store original display
        originalDisplays.set(element, element.style.display)
        
        // Check for potential issues
        const computedStyle = window.getComputedStyle(element)
        const color = computedStyle.color || ''
        const bgColor = computedStyle.backgroundColor || ''
        
        // Hide elements with problematic colors
        if (color.includes('oklab') || bgColor.includes('oklab')) {
          element.style.display = 'none'
        }
      }
    })

    // Create canvas with simplified options
    const canvas = await html2canvas(element, {
      scale: 1.5,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight,
      allowTaint: true,
      ignoreElements: (element) => {
        // Ignore elements that might cause issues
        const tagName = element.tagName?.toLowerCase()
        return tagName === 'script' || tagName === 'style' || tagName === 'link'
      }
    })

    console.log("Canvas created successfully")

    // Restore original displays
    originalDisplays.forEach((display, element) => {
      element.style.display = display
    })

    // Create PDF
    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4"
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 15

    // Add title
    pdf.setFontSize(20)
    pdf.setTextColor(33, 150, 243)
    pdf.text("Business Analysis Report", margin, margin + 10)

    pdf.setFontSize(12)
    pdf.setTextColor(100, 116, 139)
    pdf.text(`Company: ${companyName}`, margin, margin + 20)
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, margin + 28)

    // Add image
    const imgWidth = pageWidth - 2 * margin
    const imgHeight = (canvas.height * imgWidth) / canvas.width
    const maxImgHeight = pageHeight - margin - 50

    let heightLeft = imgHeight
    let position = margin + 35

    // Add image to first page
    pdf.addImage(imgData, "PNG", margin, position, imgWidth, Math.min(imgHeight, maxImgHeight))
    heightLeft -= maxImgHeight

    // Add new pages if needed
    while (heightLeft > 0) {
      position = margin - (maxImgHeight - heightLeft)
      pdf.addPage()
      pdf.addImage(imgData, "PNG", margin, position, imgWidth, Math.min(heightLeft, maxImgHeight))
      heightLeft -= maxImgHeight
    }

    // Add footer
    const totalPages = pdf.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      pdf.setFontSize(9)
      pdf.setTextColor(148, 163, 184)
      pdf.text("Generated by NexusAI Business Analytics", margin, pageHeight - 10)
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 10)
    }

    // Save PDF
    pdf.save(fileName)
    console.log("PDF exported successfully")

  } catch (error) {
    console.error("Error exporting PDF:", error)
    alert("There was an error generating the PDF. Please try again.")
  }
}
